#!/bin/bash

bosh_version=${bosh_version:-255.8}
aws_cpi_version=${aws_cpi_version:-48}
stemcell_version=${stemcell_version:-3012}

cd $HOME/Tools/bosh

if [[ ! -f bosh-${bosh_version}.tgz ]]; then
  echo "Downloading bosh-${bosh_version}.tgz"
  curl -Lo bosh-${bosh_version}.tgz \
    "https://bosh.io/d/github.com/cloudfoundry/bosh?v=${bosh_version}"
fi
if [[ ! -f bosh-aws-cpi-release-${aws_cpi_version}.tgz ]]; then
  echo "Downloading bosh-aws-cpi-release-${aws_cpi_version}.tgz"
  curl -Lo bosh-aws-cpi-release-${aws_cpi_version}.tgz \
    "http://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=${aws_cpi_version}"
fi
if [[ ! -f light-bosh-stemcell-${stemcell_version}-aws-xen-ubuntu-trusty-go_agent.tgz ]]; then
  echo "Downloading light-bosh-stemcell-${stemcell_version}-aws-xen-ubuntu-trusty-go_agent.tgz"
  curl -Lo light-bosh-stemcell-${stemcell_version}-aws-xen-ubuntu-trusty-go_agent.tgz \
    https://d26ekeud912fhb.cloudfront.net/bosh-stemcell/aws/light-bosh-stemcell-${stemcell_version}-aws-xen-ubuntu-trusty-go_agent.tgz
fi